source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.3"

# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"

gem "rss"
gem "htmlentities"
gem "view_component"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "brakeman"
gem "bundler-audit"
gem "rubocop-rails"
gem "rufus-scheduler"
gem "lograge"
gem "logstash-event"
gem "logstash-logger"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]

  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
  gem 'rack-mini-profiler', require: false
  gem 'stackprof'
  gem 'memory_profiler'

  gem "guard"
  gem "guard-puma"
  gem "guard-bundler"
  gem "better_errors"
  gem "binding_of_caller"
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
end

group :test do
  gem "selenium-webdriver"
  gem "capybara"
  gem "webdrivers"
  gem "rspec-rails"
  gem "rubocop-rspec"
end
